services:

  api:
    build:
      context: .
    restart: always
    env_file:
      - ./src/.env
    environment:
      POSTGRES_HOST: db
    command: python ./src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/code/src/
    ports:
      - 8000:8000
    depends_on:
      db:
          condition: service_healthy
      migrate:
          condition: service_completed_successfully


  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./pg_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  front:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_started

  migrate:
    build:
      context: .
    env_file:
      - ./src/.env
    environment:
      POSTGRES_HOST: db
    command: python ./src/manage.py migrate
    depends_on:
      db:
        condition: service_healthy
