# Generated by Django 5.0.2 on 2024-03-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goals_user_goalcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
