# название
name: Build and deploy action
# событие
on: [push]
# что будет происходить после пуша
jobs:
  build_and_push:
#    Обозначение ранера
    runs-on: ubuntu-latest
#    указание скриптов
    steps:
#       Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v2
#       Собераем
      - name: docker build
        run: docker build -t refusion/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
#        Логинимся в докер хаб
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#        Пушим образ в докер хаб
      - name: docker push
        run: docker push refusion/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat docker-config-ci | envsubst > deploy/docker-config
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/docker-config"
          target: "todolist_app_ci"
          strip_components: 1
#      - name: deploy app
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd todolist_app_ci
#            echo ${{ secrets.PASSWORD }} | sudo -S docker compose up -d
            

      
