# название
name: Build and deploy action
# событие
on: [push]
# что будет происходить после пуша
jobs:
  build_and_push:
#    Обозначение ранера
    runs-on: ubuntu-latest
#    указание скриптов
    steps:
#       Копируем код из репозитория в runner
      - name: clone code
        uses: workflows/checkout@v2
#       Собераем
      - name: docker build
        run: docker build -t refusion/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
#      - name: docker login
#        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#      - name: docker push
#        run: docker push todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    env:
#      DB_USER: postgres
#      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#      DB_NAME: ${{ secrets.DB_NAME }}
#    steps:
#      - name: clone code
#        uses: workflows/checkout@v2
#      - name: render configs
#        run: |
#          mkdir deploy
#          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
#          cat docker_ci_config.py | envsubst > deploy/docker_config.py
      
